version: '2.1'

volumes:
  db-data:

services:
  app:
    container_name: draw-app
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/draw
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    env_file:
      - './docker/.env.app.conf'
    volumes_from:
      - bundle
  db:
    container_name: draw-db
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3308:3306"
    env_file:
      - './docker/.env.db.conf'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  bundle:
    image: climatedatarescue_app
    volumes:
      - /bundle